[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

# Enables the usage of setuptools_scm
[tool.setuptools_scm]
"root" = "."

[tool.isort]
profile = "black"
skip_glob = ["src/usdb_dl/gui/forms", "src/usdb_dl/gui/resources"]

[tool.black]
extend-exclude = ["src/usdb_dl/gui/forms", "src/usdb_dl/gui/resources"]

[tool.pylint.master]
ignored-modules = ["PySide6.QtCore", "PySide6.QtGui", "PySide6.QtWidgets"]
ignore-paths = [
    "src/usdb_dl/gui/forms",
    "src/usdb_dl/gui/resources",
    "src/resources_rc.py",
]
# Add McCabe code complexity checker
load-plugins = """
    pylint.extensions.mccabe
    """
# The following settings modify the behavior when running pylint with pylint.extensions.docparams plugin loaded
# accept-no-param-doc = "no"
# accept-no-raise-doc = "no"
# accept-no-return-doc = "no"
# accept-no-yields-doc = "no"

[tool.pylint.messages_control]
# https://github.com/samuelcolvin/pydantic/issues/1961
extension-pkg-whitelist = "pydantic"
disable = """
    too-few-public-methods,
    logging-fstring-interpolation,
    too-many-instance-attributes,
    too-many-arguments,
    missing-function-docstring
    """

[tool.pylint.similarities]
# Exclude the following from code duplication checks
ignore-comments = "yes"
ignore-docstrings = "yes"
ignore-imports = "yes"
ignore-signatures = "yes"

[tool.mypy]
disallow_untyped_defs = true
exclude = [
    "venv",
    "log",
    "src/usdb_dl/gui/forms",
    "src/usdb_dl/gui/resources",
    "resources_rc.py",
]


[tool.pytest.ini_options]
python_classes = "!TestCase"
addopts = """
    -vv
    --junitxml=reports/pytest.xml
    --cov=usdb_dl
    --cov-config=pyproject.toml
    --cov-report xml:reports/coverage.xml
    --cov-report html:reports/coverage_html
    """

[tool.coverage.run]
branch = true
data_file = "reports/.coverage"

[tool.coverage.paths]
# Maps coverage measured in site-packages to source files in src
source = ["src/", ".tox/*/lib/python*/site-packages/"]

[tool.pydocstyle]
convention = "google"
